### ISSUE TITLE
Error when referencing missing profile

### ISSUE THREAD

**Issue by randallreedjr** [randallreedjr/git_switch#10]
Encountered an error when trying to switch profiles and specifying an incorrect name
```
$ git switch bad-profile

Git Config:
lib/git_switch/switcher.rb:58:in `name': undefined method `[]' for nil:NilClass (NoMethodError)
	from lib/git_switch/switcher.rb:44:in `set!'
```

**Comment by randallreedjr** [comment]
Fixed by #13
